resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: github_integration                       # <-- replace with your integration
      path: YehudaRosenberg/pipelines_templates    # <-- replace with your repository name
      branches:
        include: master
      buildOn:
        commit: true

  - name: new_image_name
    type: Image
    configuration:
      registry: artifactory_integration                                # <-- replace with your     MyArtifactoryifactory integration
      sourceRepository: main1-docker-alpine-local               # <-- required if registry is     MyArtifactoryifactory
      imageName: avigdor.jfrog.io/artifactory/main1-docker-alpine-local/ # < -- replace with your image path and name
      imageTag: ${run_number}
      autoPull: true
      

pipelines:
  - name: pipeline_build_and_push_yehuda
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: avigdor.jfrog.io/ui/repos/tree/General/main1-docker-alpine-local  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: artifactory_integration                            # <-- replace with your     MyArtifactoryifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: main1-docker-alpine-local
          integrations:
            - name: artifactory_integration                            # <-- new test replace with your     MyArtifactoryifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: new_image_name